[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "chromium"
]

[phases.install]
cmds = [
  "python -m pip install --break-system-packages -r requirements.txt",
  "python -m playwright install chromium"
]

[start]
cmd = "python app.py"
