[variables]
PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "chromium"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt",
  "playwright install chromium"
]

[start]
cmd = "python app.py"
